-- ==============================================================================
-- Database Schema for Resume Analyzer Application
-- Target Database: PostgreSQL 15+
-- ==============================================================================

-- Enable UUID extension for auto-generating UUIDs if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------------------------
-- 1. Table: user_info
-- Entity Source: com.sprint.analyzer.entity.User
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_info (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL, -- Bcrypt hash, maps to User.java's password property
    phone VARCHAR(20),
    bucket_name VARCHAR(255) NOT NULL UNIQUE, -- User-dedicated S3 bucket name
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified_at TIMESTAMP,
    role VARCHAR(32) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT chk_user_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE INDEX IF NOT EXISTS idx_user_info_email ON user_info(email);

COMMENT ON TABLE user_info IS 'Stores user account information and roles';
COMMENT ON COLUMN user_info.id IS 'Unique identifier (UUID)';
COMMENT ON COLUMN user_info.email IS 'User email address (unique, used for login)';
COMMENT ON COLUMN user_info.name IS 'User full name';
COMMENT ON COLUMN user_info.password IS 'Bcrypt hashed password';
COMMENT ON COLUMN user_info.phone IS 'User phone number (optional)';
COMMENT ON COLUMN user_info.bucket_name IS 'Dedicated AWS S3 bucket name for user''s resumes';
COMMENT ON COLUMN user_info.email_verified IS 'True if the user has verified their email address';
COMMENT ON COLUMN user_info.email_verified_at IS 'Timestamp when the user verified their email';
COMMENT ON COLUMN user_info.role IS 'User permission role (USER, ADMIN)';
COMMENT ON COLUMN user_info.created_at IS 'Account creation timestamp';


-- ------------------------------------------------------------------------------
-- 2. Table: resume_metadata
-- Entity Source: com.sprint.analyzer.entity.ResumeMetadata
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resume_metadata (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    original_filename TEXT NOT NULL,
    s3_key TEXT,
    file_type VARCHAR(20),
    token_count INT,
    status VARCHAR(50),
    overall_score INT,
    resume_hash VARCHAR(64), -- SHA-256 hash to identify duplicates
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_resume_user FOREIGN KEY (user_id) 
        REFERENCES user_info(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_resume_metadata_user_id ON resume_metadata(user_id);
CREATE INDEX IF NOT EXISTS idx_resume_metadata_s3_key ON resume_metadata(s3_key);
CREATE INDEX IF NOT EXISTS idx_resume_metadata_status ON resume_metadata(status);
CREATE INDEX IF NOT EXISTS idx_resume_metadata_created_at ON resume_metadata(created_at);

COMMENT ON TABLE resume_metadata IS 'Stores metadata of uploaded resumes and tracking processing status';
COMMENT ON COLUMN resume_metadata.id IS 'Unique identifier (UUID)';
COMMENT ON COLUMN resume_metadata.user_id IS 'Owner of the resume';
COMMENT ON COLUMN resume_metadata.original_filename IS 'Uploaded original filename';
COMMENT ON COLUMN resume_metadata.s3_key IS 'Path of the PDF/DOCX file in AWS S3';
COMMENT ON COLUMN resume_metadata.file_type IS 'File type (e.g. pdf, docx)';
COMMENT ON COLUMN resume_metadata.token_count IS 'Total token count of the document text';
COMMENT ON COLUMN resume_metadata.status IS 'Processing status (PENDING, PROCESSING, COMPLETED, FAILED)';
COMMENT ON COLUMN resume_metadata.overall_score IS 'Overall score out of 100 generated by LLM';
COMMENT ON COLUMN resume_metadata.resume_hash IS 'SHA-256 file content hash';
COMMENT ON COLUMN resume_metadata.created_at IS 'Upload date and time';


-- ------------------------------------------------------------------------------
-- 3. Table: email_verification_token
-- Entity Source: com.sprint.analyzer.entity.EmailVerificationToken
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS email_verification_token (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    purpose VARCHAR(50) NOT NULL DEFAULT 'EMAIL_VERIFICATION',
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_evt_user FOREIGN KEY (user_id) 
        REFERENCES user_info(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_evt_token ON email_verification_token(token);
CREATE INDEX IF NOT EXISTS idx_evt_user_id ON email_verification_token(user_id);

COMMENT ON TABLE email_verification_token IS 'Tokens used for email verification or password reset flows';
COMMENT ON COLUMN email_verification_token.id IS 'Unique token record ID';
COMMENT ON COLUMN email_verification_token.user_id IS 'Target user receiving token verification';
COMMENT ON COLUMN email_verification_token.token IS 'Cryptographically secure random token string';
COMMENT ON COLUMN email_verification_token.purpose IS 'Verification purpose (e.g. EMAIL_VERIFICATION, PASSWORD_RESET)';
COMMENT ON COLUMN email_verification_token.expires_at IS 'Expiration timestamp';
COMMENT ON COLUMN email_verification_token.used_at IS 'Timestamp when the token was successfully verified/used';
COMMENT ON COLUMN email_verification_token.created_at IS 'Timestamp of token generation';


-- ------------------------------------------------------------------------------
-- 4. Table: feature_flag
-- Entity Source: com.sprint.analyzer.entity.FeatureFlag
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feature_flag (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_feature_flag_name ON feature_flag(name);

-- Seed initial default flags
INSERT INTO feature_flag (id, name, enabled, description)
VALUES (gen_random_uuid(), 'EMAIL_VERIFICATION_ENABLED', TRUE, 
        'Send verification email on signup and require verified email to log in.')
ON CONFLICT (name) DO NOTHING;

COMMENT ON TABLE feature_flag IS 'System configuration and feature flags';
COMMENT ON COLUMN feature_flag.id IS 'Unique feature flag ID';
COMMENT ON COLUMN feature_flag.name IS 'Name of the flag in UPPER_SNAKE_CASE';
COMMENT ON COLUMN feature_flag.enabled IS 'True if flag is enabled';
COMMENT ON COLUMN feature_flag.description IS 'Detail of features controlled';
COMMENT ON COLUMN feature_flag.created_at IS 'Timestamp of flag creation';
COMMENT ON COLUMN feature_flag.updated_at IS 'Timestamp of last update';


-- ------------------------------------------------------------------------------
-- 5. Table: jwt_blacklist
-- Entity Source: com.sprint.analyzer.entity.JwtBlacklist
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS jwt_blacklist (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token VARCHAR(512) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jwt_blacklist_token ON jwt_blacklist(token);
CREATE INDEX IF NOT EXISTS idx_jwt_blacklist_expiry_date ON jwt_blacklist(expiry_date);

COMMENT ON TABLE jwt_blacklist IS 'Invalidated tokens due to user logout';
COMMENT ON COLUMN jwt_blacklist.id IS 'Unique record identifier';
COMMENT ON COLUMN jwt_blacklist.token IS 'Full raw JWT text';
COMMENT ON COLUMN jwt_blacklist.expiry_date IS 'Natural token expiration timestamp';
COMMENT ON COLUMN jwt_blacklist.created_at IS 'Timestamp when token was blacklisted';


-- ------------------------------------------------------------------------------
-- 6. Table: resume_section_score
-- Entity Source: com.sprint.analyzer.entity.ResumeSectionScore
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resume_section_score (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    resume_id UUID NOT NULL,
    user_id UUID NOT NULL,
    section_name VARCHAR(100) NOT NULL,
    section_hash VARCHAR(64),
    score INT,
    feedback TEXT,
    strengths TEXT,       -- Serialized list of strengths
    improvements TEXT,    -- Serialized list of improvements
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_section_score_resume FOREIGN KEY (resume_id) 
        REFERENCES resume_metadata(id) ON DELETE CASCADE,
    CONSTRAINT fk_section_score_user FOREIGN KEY (user_id) 
        REFERENCES user_info(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_resume_section_score_resume_id ON resume_section_score(resume_id);
CREATE INDEX IF NOT EXISTS idx_resume_section_score_user_id ON resume_section_score(user_id);

COMMENT ON TABLE resume_section_score IS 'Granular evaluation scores of distinct resume sections';
COMMENT ON COLUMN resume_section_score.id IS 'Unique identifier';
COMMENT ON COLUMN resume_section_score.resume_id IS 'Associated resume';
COMMENT ON COLUMN resume_section_score.user_id IS 'Owner of the resume';
COMMENT ON COLUMN resume_section_score.section_name IS 'Section name (e.g. Work Experience, Education)';
COMMENT ON COLUMN resume_section_score.section_hash IS 'SHA-256 of the section text to check for edits';
COMMENT ON COLUMN resume_section_score.score IS 'Section score from 0 to 100';
COMMENT ON COLUMN resume_section_score.feedback IS 'Detailed text feedback';
COMMENT ON COLUMN resume_section_score.strengths IS 'Serialized string array of strengths';
COMMENT ON COLUMN resume_section_score.improvements IS 'Serialized string array of improvement areas';
COMMENT ON COLUMN resume_section_score.created_at IS 'Assessment generation date';
